SOLVER:
  BATCH_SIZE: 8
  MAX_EPOCH: 200
  LR: 5e-5
  SEED: 12

DA:
  TASK: False
  USE: False

DECODER:
  BINARY: 1

# Config below only when you use comet
COMET:
  PROJECT_NAME: "DrugBAN_Vanilla"
  TAG: "Non_DA"

